

drop trigger if exists invoice.trig_saleinvoice_insert;

DELIMITER $$
CREATE TRIGGER `invoice`.`trig_saleinvoice_insert` AFTER INSERT
ON `invoice`.`saleinvoice`
FOR EACH ROW BEGIN
    INSERT INTO `data_warehouse2`.`saleinvoice`
        (
            `CID`,
            `AGENTCODE`,
            `AUTHSTATE`,
            `AUTHTIME`,
            `AUTHUSERNAME`,
            `BATCHID`,
            `BILLID`,
            `BILLNO`,
            `BUYERADDTEL`,
            `BUYERBANKNO`,
            `BUYERNAME`,
            `BUYERNO`,
            `BUYERTAXNO`,
            `CANCELFLAG`,
            `CARRIERTAXNO`,
            `CD`,
            `CHECKCODE`,
            `CHECKRESULT`,
            `CHECKSTATE`,
            `CHECKTIME`,
            `CIPHERTEXT`,
            `CJHM`,
            `COMMENTS`,
            `CONFIRMSTATE`,
            `CREATETIME`,
            `DETAILLISTFLAG`,
            `EMAIL`,
            `ENCRYPTIONVER`,
            `FDJHM`,
            `FHRSBH`,
            `FORWORDSTATE`,
            `FORWORDTIME`,
            `GATHERINGPERSON`,
            `HGZH`,
            `IMGSTATE`,
            `INCOMINGSTATE`,
            `INCOMINGTIME`,
            `INCOMINGUSERNAME`,
            `INPUTPERSON`,
            `INVOICECODE`,
            `INVOICECONTENT`,
            `INVOICEDATE`,
            `INVOICEID`,
            `INVOICENO`,
            `INVOICETYPE`,
            `JZTYPE`,
            `KPZDBS`,
            `LOGNO`,
            `MACHINENO`,
            `MAKEINVOICEDEVICENO`,
            `MAKEINVOICEPERSON`,
            `MOBILENO`,
            `PDFURL`,
            `PRINTFLAG`,
            `PUSHSTATE`,
            `PUSHTIME`,
            `QYD`,
            `RECHECKPERSON`,
            `REPAIRFLAG`,
            `RESPONECODE`,
            `RESPONEEXPLAIN`,
            `SALEBILLNO`,
            `SELLERADDTEL`,
            `SELLERBANKNO`,
            `SELLERNAME`,
            `SELLERTAXNO`,
            `SENTERRTIMES`,
            `SENTOPERATOR`,
            `SENTTIME`,
            `SENTTOBANK`,
            `SHRSBH`,
            `SKTYPE`,
            `SOURCE`,
            `SPSM`,
            `SRCTYPE`,
            `TAXOFFICECODE`,
            `TAXRATE`,
            `TOTALAMOUNT`,
            `TOTALTAX`,
            `WRITEBACKSTATE`,
            `WRITEBACKTIME`,
            `XCRS`,
            `XFDH`,
            `XFDZ`,
            `YSHWXX`,
            `YYZZH`,
            `ZH`,
            `ZYSPMC`,
            `INVOICEDATEMONTH`
        )
    VALUES
        (
            new.`CID`,
            new.`AGENTCODE`,
            new.`AUTHSTATE`,
            new.`AUTHTIME`,
            new.`AUTHUSERNAME`,
            new.`BATCHID`,
            new.`BILLID`,
            new.`BILLNO`,
            new.`BUYERADDTEL`,
            new.`BUYERBANKNO`,
            new.`BUYERNAME`,
            new.`BUYERNO`,
            new.`BUYERTAXNO`,
            new.`CANCELFLAG`,
            new.`CARRIERTAXNO`,
            new.`CD`,
            new.`CHECKCODE`,
            new.`CHECKRESULT`,
            new.`CHECKSTATE`,
            new.`CHECKTIME`,
            new.`CIPHERTEXT`,
            new.`CJHM`,
            new.`COMMENTS`,
            new.`CONFIRMSTATE`,
            new.`CREATETIME`,
            new.`DETAILLISTFLAG`,
            new.`EMAIL`,
            new.`ENCRYPTIONVER`,
            new.`FDJHM`,
            new.`FHRSBH`,
            new.`FORWORDSTATE`,
            new.`FORWORDTIME`,
            new.`GATHERINGPERSON`,
            new.`HGZH`,
            new.`IMGSTATE`,
            new.`INCOMINGSTATE`,
            new.`INCOMINGTIME`,
            new.`INCOMINGUSERNAME`,
            new.`INPUTPERSON`,
            new.`INVOICECODE`,
            new.`INVOICECONTENT`,
            new.`INVOICEDATE`,
            new.`INVOICEID`,
            new.`INVOICENO`,
            new.`INVOICETYPE`,
            new.`JZTYPE`,
            new.`KPZDBS`,
            new.`LOGNO`,
            new.`MACHINENO`,
            new.`MAKEINVOICEDEVICENO`,
            new.`MAKEINVOICEPERSON`,
            new.`MOBILENO`,
            new.`PDFURL`,
            new.`PRINTFLAG`,
            new.`PUSHSTATE`,
            new.`PUSHTIME`,
            new.`QYD`,
            new.`RECHECKPERSON`,
            new.`REPAIRFLAG`,
            new.`RESPONECODE`,
            new.`RESPONEEXPLAIN`,
            new.`SALEBILLNO`,
            new.`SELLERADDTEL`,
            new.`SELLERBANKNO`,
            new.`SELLERNAME`,
            new.`SELLERTAXNO`,
            new.`SENTERRTIMES`,
            new.`SENTOPERATOR`,
            new.`SENTTIME`,
            new.`SENTTOBANK`,
            new.`SHRSBH`,
            new.`SKTYPE`,
            new.`SOURCE`,
            new.`SPSM`,
            new.`SRCTYPE`,
            new.`TAXOFFICECODE`,
            new.`TAXRATE`,
            new.`TOTALAMOUNT`,
            new.`TOTALTAX`,
            new.`WRITEBACKSTATE`,
            new.`WRITEBACKTIME`,
            new.`XCRS`,
            new.`XFDH`,
            new.`XFDZ`,
            new.`YSHWXX`,
            new.`YYZZH`,
            new.`ZH`,
            new.`ZYSPMC`,
            year(new.`INVOICEDATE`)*12+month(new.`INVOICEDATE`)
         )
    ON DUPLICATE KEY UPDATE
            `CID`               =	new.`CID`,
            `AGENTCODE`         =	new.`AGENTCODE`,
            `AUTHSTATE`         =	new.`AUTHSTATE`,
            `AUTHTIME`          =	new.`AUTHTIME`,
            `AUTHUSERNAME`      =	new.`AUTHUSERNAME`,
            `BATCHID`           =	new.`BATCHID`,
            `BILLID`            =	new.`BILLID`,
            `BILLNO`            =	new.`BILLNO`,
            `BUYERADDTEL`       =	new.`BUYERADDTEL`,
            `BUYERBANKNO`       =	new.`BUYERBANKNO`,
            `BUYERNAME`         =	new.`BUYERNAME`,
            `BUYERNO`           =	new.`BUYERNO`,
            `BUYERTAXNO`        =	new.`BUYERTAXNO`,
            `CANCELFLAG`        =	new.`CANCELFLAG`,
            `CARRIERTAXNO`      =	new.`CARRIERTAXNO`,
            `CD`                =	new.`CD`,
            `CHECKCODE`         =	new.`CHECKCODE`,
            `CHECKRESULT`       =	new.`CHECKRESULT`,
            `CHECKSTATE`        =	new.`CHECKSTATE`,
            `CHECKTIME`         =	new.`CHECKTIME`,
            `CIPHERTEXT`        =	new.`CIPHERTEXT`,
            `CJHM`              =	new.`CJHM`,
            `COMMENTS`          =	new.`COMMENTS`,
            `CONFIRMSTATE`      =	new.`CONFIRMSTATE`,
            `CREATETIME`        =	new.`CREATETIME`,
            `DETAILLISTFLAG`    =	new.`DETAILLISTFLAG`,
            `EMAIL`             =	new.`EMAIL`,
            `ENCRYPTIONVER`     =	new.`ENCRYPTIONVER`,
            `FDJHM`             =	new.`FDJHM`,
            `FHRSBH`            =	new.`FHRSBH`,
            `FORWORDSTATE`      =	new.`FORWORDSTATE`,
            `FORWORDTIME`       =	new.`FORWORDTIME`,
            `GATHERINGPERSON`   =	new.`GATHERINGPERSON`,
            `HGZH`              =	new.`HGZH`,
            `IMGSTATE`          =	new.`IMGSTATE`,
            `INCOMINGSTATE`     =	new.`INCOMINGSTATE`,
            `INCOMINGTIME`      =	new.`INCOMINGTIME`,
            `INCOMINGUSERNAME`  =	new.`INCOMINGUSERNAME`,
            `INPUTPERSON`       =	new.`INPUTPERSON`,
            `INVOICECODE`       =	new.`INVOICECODE`,
            `INVOICECONTENT`    =	new.`INVOICECONTENT`,
            `INVOICEDATE`       =	new.`INVOICEDATE`,
            `INVOICEID`         =	new.`INVOICEID`,
            `INVOICENO`         =	new.`INVOICENO`,
            `INVOICETYPE`       =	new.`INVOICETYPE`,
            `JZTYPE`            =	new.`JZTYPE`,
            `KPZDBS`            =	new.`KPZDBS`,
            `LOGNO`             =	new.`LOGNO`,
            `MACHINENO`         =	new.`MACHINENO`,
            `MAKEINVOICEDEVICENO`=	new.`MAKEINVOICEDEVICENO`,
            `MAKEINVOICEPERSON` =	new.`MAKEINVOICEPERSON`,
            `MOBILENO`          =	new.`MOBILENO`,
            `PDFURL`            =	new.`PDFURL`,
            `PRINTFLAG`         =	new.`PRINTFLAG`,
            `PUSHSTATE`         =	new.`PUSHSTATE`,
            `PUSHTIME`          =	new.`PUSHTIME`,
            `QYD`               =	new.`QYD`,
            `RECHECKPERSON`     =	new.`RECHECKPERSON`,
            `REPAIRFLAG`        =	new.`REPAIRFLAG`,
            `RESPONECODE`       =	new.`RESPONECODE`,
            `RESPONEEXPLAIN`    =	new.`RESPONEEXPLAIN`,
            `SALEBILLNO`        =	new.`SALEBILLNO`,
            `SELLERADDTEL`      =	new.`SELLERADDTEL`,
            `SELLERBANKNO`      =	new.`SELLERBANKNO`,
            `SELLERNAME`        =	new.`SELLERNAME`,
            `SELLERTAXNO`       =	new.`SELLERTAXNO`,
            `SENTERRTIMES`      =	new.`SENTERRTIMES`,
            `SENTOPERATOR`      =	new.`SENTOPERATOR`,
            `SENTTIME`          =	new.`SENTTIME`,
            `SENTTOBANK`        =	new.`SENTTOBANK`,
            `SHRSBH`            =	new.`SHRSBH`,
            `SKTYPE`            =	new.`SKTYPE`,
            `SOURCE`            =	new.`SOURCE`,
            `SPSM`              =	new.`SPSM`,
            `SRCTYPE`           =	new.`SRCTYPE`,
            `TAXOFFICECODE`     =	new.`TAXOFFICECODE`,
            `TAXRATE`           =	new.`TAXRATE`,
            `TOTALAMOUNT`       =	new.`TOTALAMOUNT`,
            `TOTALTAX`          =	new.`TOTALTAX`,
            `WRITEBACKSTATE`    =	new.`WRITEBACKSTATE`,
            `WRITEBACKTIME`     =	new.`WRITEBACKTIME`,
            `XCRS`              =	new.`XCRS`,
            `XFDH`              =	new.`XFDH`,
            `XFDZ`              =	new.`XFDZ`,
            `YSHWXX`            =	new.`YSHWXX`,
            `YYZZH`             =	new.`YYZZH`,
            `ZH`                =	new.`ZH`,
            `ZYSPMC`            =	new.`ZYSPMC`,
            `INVOICEDATEMONTH`  =	year(new.`INVOICEDATE`)*12+month(new.`INVOICEDATE`) ;
END$$
DELIMITER ;


drop trigger if exists invoice.trig_saleinvoice_update;
DELIMITER $$
CREATE TRIGGER `invoice`.`trig_saleinvoice_update` AFTER UPDATE
ON `invoice`.`saleinvoice`
FOR EACH ROW BEGIN
    INSERT INTO `data_warehouse2`.`saleinvoice`
        (
            `CID`,
            `AGENTCODE`,
            `AUTHSTATE`,
            `AUTHTIME`,
            `AUTHUSERNAME`,
            `BATCHID`,
            `BILLID`,
            `BILLNO`,
            `BUYERADDTEL`,
            `BUYERBANKNO`,
            `BUYERNAME`,
            `BUYERNO`,
            `BUYERTAXNO`,
            `CANCELFLAG`,
            `CARRIERTAXNO`,
            `CD`,
            `CHECKCODE`,
            `CHECKRESULT`,
            `CHECKSTATE`,
            `CHECKTIME`,
            `CIPHERTEXT`,
            `CJHM`,
            `COMMENTS`,
            `CONFIRMSTATE`,
            `CREATETIME`,
            `DETAILLISTFLAG`,
            `EMAIL`,
            `ENCRYPTIONVER`,
            `FDJHM`,
            `FHRSBH`,
            `FORWORDSTATE`,
            `FORWORDTIME`,
            `GATHERINGPERSON`,
            `HGZH`,
            `IMGSTATE`,
            `INCOMINGSTATE`,
            `INCOMINGTIME`,
            `INCOMINGUSERNAME`,
            `INPUTPERSON`,
            `INVOICECODE`,
            `INVOICECONTENT`,
            `INVOICEDATE`,
            `INVOICEID`,
            `INVOICENO`,
            `INVOICETYPE`,
            `JZTYPE`,
            `KPZDBS`,
            `LOGNO`,
            `MACHINENO`,
            `MAKEINVOICEDEVICENO`,
            `MAKEINVOICEPERSON`,
            `MOBILENO`,
            `PDFURL`,
            `PRINTFLAG`,
            `PUSHSTATE`,
            `PUSHTIME`,
            `QYD`,
            `RECHECKPERSON`,
            `REPAIRFLAG`,
            `RESPONECODE`,
            `RESPONEEXPLAIN`,
            `SALEBILLNO`,
            `SELLERADDTEL`,
            `SELLERBANKNO`,
            `SELLERNAME`,
            `SELLERTAXNO`,
            `SENTERRTIMES`,
            `SENTOPERATOR`,
            `SENTTIME`,
            `SENTTOBANK`,
            `SHRSBH`,
            `SKTYPE`,
            `SOURCE`,
            `SPSM`,
            `SRCTYPE`,
            `TAXOFFICECODE`,
            `TAXRATE`,
            `TOTALAMOUNT`,
            `TOTALTAX`,
            `WRITEBACKSTATE`,
            `WRITEBACKTIME`,
            `XCRS`,
            `XFDH`,
            `XFDZ`,
            `YSHWXX`,
            `YYZZH`,
            `ZH`,
            `ZYSPMC`,
            `INVOICEDATEMONTH`
        )
    VALUES
        (
            new.`CID`,
            new.`AGENTCODE`,
            new.`AUTHSTATE`,
            new.`AUTHTIME`,
            new.`AUTHUSERNAME`,
            new.`BATCHID`,
            new.`BILLID`,
            new.`BILLNO`,
            new.`BUYERADDTEL`,
            new.`BUYERBANKNO`,
            new.`BUYERNAME`,
            new.`BUYERNO`,
            new.`BUYERTAXNO`,
            new.`CANCELFLAG`,
            new.`CARRIERTAXNO`,
            new.`CD`,
            new.`CHECKCODE`,
            new.`CHECKRESULT`,
            new.`CHECKSTATE`,
            new.`CHECKTIME`,
            new.`CIPHERTEXT`,
            new.`CJHM`,
            new.`COMMENTS`,
            new.`CONFIRMSTATE`,
            new.`CREATETIME`,
            new.`DETAILLISTFLAG`,
            new.`EMAIL`,
            new.`ENCRYPTIONVER`,
            new.`FDJHM`,
            new.`FHRSBH`,
            new.`FORWORDSTATE`,
            new.`FORWORDTIME`,
            new.`GATHERINGPERSON`,
            new.`HGZH`,
            new.`IMGSTATE`,
            new.`INCOMINGSTATE`,
            new.`INCOMINGTIME`,
            new.`INCOMINGUSERNAME`,
            new.`INPUTPERSON`,
            new.`INVOICECODE`,
            new.`INVOICECONTENT`,
            new.`INVOICEDATE`,
            new.`INVOICEID`,
            new.`INVOICENO`,
            new.`INVOICETYPE`,
            new.`JZTYPE`,
            new.`KPZDBS`,
            new.`LOGNO`,
            new.`MACHINENO`,
            new.`MAKEINVOICEDEVICENO`,
            new.`MAKEINVOICEPERSON`,
            new.`MOBILENO`,
            new.`PDFURL`,
            new.`PRINTFLAG`,
            new.`PUSHSTATE`,
            new.`PUSHTIME`,
            new.`QYD`,
            new.`RECHECKPERSON`,
            new.`REPAIRFLAG`,
            new.`RESPONECODE`,
            new.`RESPONEEXPLAIN`,
            new.`SALEBILLNO`,
            new.`SELLERADDTEL`,
            new.`SELLERBANKNO`,
            new.`SELLERNAME`,
            new.`SELLERTAXNO`,
            new.`SENTERRTIMES`,
            new.`SENTOPERATOR`,
            new.`SENTTIME`,
            new.`SENTTOBANK`,
            new.`SHRSBH`,
            new.`SKTYPE`,
            new.`SOURCE`,
            new.`SPSM`,
            new.`SRCTYPE`,
            new.`TAXOFFICECODE`,
            new.`TAXRATE`,
            new.`TOTALAMOUNT`,
            new.`TOTALTAX`,
            new.`WRITEBACKSTATE`,
            new.`WRITEBACKTIME`,
            new.`XCRS`,
            new.`XFDH`,
            new.`XFDZ`,
            new.`YSHWXX`,
            new.`YYZZH`,
            new.`ZH`,
            new.`ZYSPMC`,
            year(new.`INVOICEDATE`)*12+month(new.`INVOICEDATE`)
         )
    ON DUPLICATE KEY UPDATE
            `CID`               =	new.`CID`,
            `AGENTCODE`         =	new.`AGENTCODE`,
            `AUTHSTATE`         =	new.`AUTHSTATE`,
            `AUTHTIME`          =	new.`AUTHTIME`,
            `AUTHUSERNAME`      =	new.`AUTHUSERNAME`,
            `BATCHID`           =	new.`BATCHID`,
            `BILLID`            =	new.`BILLID`,
            `BILLNO`            =	new.`BILLNO`,
            `BUYERADDTEL`       =	new.`BUYERADDTEL`,
            `BUYERBANKNO`       =	new.`BUYERBANKNO`,
            `BUYERNAME`         =	new.`BUYERNAME`,
            `BUYERNO`           =	new.`BUYERNO`,
            `BUYERTAXNO`        =	new.`BUYERTAXNO`,
            `CANCELFLAG`        =	new.`CANCELFLAG`,
            `CARRIERTAXNO`      =	new.`CARRIERTAXNO`,
            `CD`                =	new.`CD`,
            `CHECKCODE`         =	new.`CHECKCODE`,
            `CHECKRESULT`       =	new.`CHECKRESULT`,
            `CHECKSTATE`        =	new.`CHECKSTATE`,
            `CHECKTIME`         =	new.`CHECKTIME`,
            `CIPHERTEXT`        =	new.`CIPHERTEXT`,
            `CJHM`              =	new.`CJHM`,
            `COMMENTS`          =	new.`COMMENTS`,
            `CONFIRMSTATE`      =	new.`CONFIRMSTATE`,
            `CREATETIME`        =	new.`CREATETIME`,
            `DETAILLISTFLAG`    =	new.`DETAILLISTFLAG`,
            `EMAIL`             =	new.`EMAIL`,
            `ENCRYPTIONVER`     =	new.`ENCRYPTIONVER`,
            `FDJHM`             =	new.`FDJHM`,
            `FHRSBH`            =	new.`FHRSBH`,
            `FORWORDSTATE`      =	new.`FORWORDSTATE`,
            `FORWORDTIME`       =	new.`FORWORDTIME`,
            `GATHERINGPERSON`   =	new.`GATHERINGPERSON`,
            `HGZH`              =	new.`HGZH`,
            `IMGSTATE`          =	new.`IMGSTATE`,
            `INCOMINGSTATE`     =	new.`INCOMINGSTATE`,
            `INCOMINGTIME`      =	new.`INCOMINGTIME`,
            `INCOMINGUSERNAME`  =	new.`INCOMINGUSERNAME`,
            `INPUTPERSON`       =	new.`INPUTPERSON`,
            `INVOICECODE`       =	new.`INVOICECODE`,
            `INVOICECONTENT`    =	new.`INVOICECONTENT`,
            `INVOICEDATE`       =	new.`INVOICEDATE`,
            `INVOICEID`         =	new.`INVOICEID`,
            `INVOICENO`         =	new.`INVOICENO`,
            `INVOICETYPE`       =	new.`INVOICETYPE`,
            `JZTYPE`            =	new.`JZTYPE`,
            `KPZDBS`            =	new.`KPZDBS`,
            `LOGNO`             =	new.`LOGNO`,
            `MACHINENO`         =	new.`MACHINENO`,
            `MAKEINVOICEDEVICENO`=	new.`MAKEINVOICEDEVICENO`,
            `MAKEINVOICEPERSON` =	new.`MAKEINVOICEPERSON`,
            `MOBILENO`          =	new.`MOBILENO`,
            `PDFURL`            =	new.`PDFURL`,
            `PRINTFLAG`         =	new.`PRINTFLAG`,
            `PUSHSTATE`         =	new.`PUSHSTATE`,
            `PUSHTIME`          =	new.`PUSHTIME`,
            `QYD`               =	new.`QYD`,
            `RECHECKPERSON`     =	new.`RECHECKPERSON`,
            `REPAIRFLAG`        =	new.`REPAIRFLAG`,
            `RESPONECODE`       =	new.`RESPONECODE`,
            `RESPONEEXPLAIN`    =	new.`RESPONEEXPLAIN`,
            `SALEBILLNO`        =	new.`SALEBILLNO`,
            `SELLERADDTEL`      =	new.`SELLERADDTEL`,
            `SELLERBANKNO`      =	new.`SELLERBANKNO`,
            `SELLERNAME`        =	new.`SELLERNAME`,
            `SELLERTAXNO`       =	new.`SELLERTAXNO`,
            `SENTERRTIMES`      =	new.`SENTERRTIMES`,
            `SENTOPERATOR`      =	new.`SENTOPERATOR`,
            `SENTTIME`          =	new.`SENTTIME`,
            `SENTTOBANK`        =	new.`SENTTOBANK`,
            `SHRSBH`            =	new.`SHRSBH`,
            `SKTYPE`            =	new.`SKTYPE`,
            `SOURCE`            =	new.`SOURCE`,
            `SPSM`              =	new.`SPSM`,
            `SRCTYPE`           =	new.`SRCTYPE`,
            `TAXOFFICECODE`     =	new.`TAXOFFICECODE`,
            `TAXRATE`           =	new.`TAXRATE`,
            `TOTALAMOUNT`       =	new.`TOTALAMOUNT`,
            `TOTALTAX`          =	new.`TOTALTAX`,
            `WRITEBACKSTATE`    =	new.`WRITEBACKSTATE`,
            `WRITEBACKTIME`     =	new.`WRITEBACKTIME`,
            `XCRS`              =	new.`XCRS`,
            `XFDH`              =	new.`XFDH`,
            `XFDZ`              =	new.`XFDZ`,
            `YSHWXX`            =	new.`YSHWXX`,
            `YYZZH`             =	new.`YYZZH`,
            `ZH`                =	new.`ZH`,
            `ZYSPMC`            =	new.`ZYSPMC`,
            `INVOICEDATEMONTH`  =	year(new.`INVOICEDATE`)*12+month(new.`INVOICEDATE`) ;
END$$
DELIMITER ;